[workspace]
authors = [
    "Daniel San José Pro <42489409+danielsanjosepro@users.noreply.github.com>",
]
name = "franka_ros2_pixi"
version = "0.1.0"
channels = [
    "https://fast.prefix.dev/conda-forge",
    "https://conda.anaconda.org/pytorch",
    "https://conda.anaconda.org/nvidia",
]
platforms = ["linux-64"]

[activation]
scripts = ["set_ros_env.sh", "ros_ws/install/setup.sh"]

[dependencies]
python = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
pytorch-cuda = ">=12.4,<13"
cuda-version = "*"
cudnn = ">=8.9,<9"
pip = ">=25.1.1,<26"
typing_inspect = ">=0.9.0,<0.10"
libstdcxx-ng = ">=15.1.0,<16"
datasets = ">=3.6.0,<4"
joblib = ">=1.5.1,<2"
tifffile = ">=2025.6.11,<2026"
cuda-nvcc = ">=12.4.131,<13"

[pypi-dependencies]
debugpy = ">=1.8.14,<2"

[target.linux.dependencies]
libgl-devel = "*"

[environments]
jazzy-only = { features = ["jazzy", "dev", "extra"] }
jazzy-crisp = { features = ["jazzy", "dev", "extra", "crisp"] }
jazzy = { features = [
    "jazzy",
    "dev",
    "extra",
    "crisp",
    "lerobot",
    "pose_estimation",
] }

# jazzy
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.7.0,<4"
poco = ">=1.14.2,<2"
ros-jazzy-ament-clang-format = ">=0.17.2,<0.18"
ros-jazzy-desktop = "*"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-moveit-core = ">=2.12.3,<3"
ros-jazzy-moveit-kinematics = ">=2.12.3,<3"
ros-jazzy-moveit-planners-ompl = ">=2.12.3,<3"
ros-jazzy-moveit-ros-move-group = ">=2.12.3,<3"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-rmw-zenoh-cpp = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-control-cmake = ">=0.2.1,<0.3"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-xacro = ">=2.0.13,<3"
rosdep = "*"

[feature.jazzy.tasks]
clone = "git clone https://github.com/frankarobotics/franka_ros2.git -b jazzy src/franka_ros2 && git clone https://github.com/frankarobotics/franka_description.git src/franka_description && git clone --recurse-submodules https://github.com/frankarobotics/libfranka.git src/libfranka"
update-libfranka = "cd src/libfranka && git submodule update --init --recursive && cd ../../"
apply-patches = "bash scripts/apply_patches.sh"
ignore-gazebo = "touch src/franka_ros2/franka_gazebo/COLCON_IGNORE"
build = "colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev"
clone-crisp = "git clone https://github.com/utiasdsl/crisp_controllers.git src/crisp_controllers"
setup = { depends-on = [
    "clone",
    "update-libfranka",
    "apply-patches",
    "ignore-gazebo",
    "build",
] }
franka = "ros2 launch scripts/launch/franka.launch.py"


[feature.lerobot.dependencies]
pynput = "*"
rerun-sdk = "==0.22.0"

[feature.lerobot.pypi-dependencies]
lerobot = { git = "https://github.com/huggingface/lerobot", rev = "dacd1d7f5c719c3e56d7b7154a751bef6d5bd23c", extras = [
    "smolvla",
] }
rich = ">=14.0.0, <15"
# triton = "==3.5.1"
"torch" = { version = "==2.7.0", index = "https://download.pytorch.org/whl/cu128" }
"torchvision" = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
"torchaudio" = { version = "*", index = "https://download.pytorch.org/whl/cu128" }


[feature.dev.pypi-dependencies]
ruff = "*"
bumpver = "*"
build = "*"
twine = "*"
pre-commit = "*"
pytest = "*"     # for testing

[feature.extra.pypi-dependencies]
rich = "*"       # For nice prints
matplotlib = "*" # to do some plots

[feature.crisp.pypi-dependencies]
crisp_drl = { path = ".", editable = true }
crisp_gym = { path = "../crisp_gym", editable = true }
crisp_python = { path = "../crisp_py", editable = true }
tensorboard = ">=2.20.0, <3"
gymnasium = { version = ">=0.29.1, <2", extras = ["classic-control"] }
mujid = { path = "../mujid_realWorldDRL", editable = true }

[feature.crisp.system-requirements]
cuda = "12.0"

[feature.pose_estimation.pypi-dependencies]
"decord" = "*"
pycocotools = "*"
sam3 = { path = "./sam3", editable = true }
pyvista = "*"
