[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crisp_drl"
version = "0.1.0"
description = "Deep Reinforcement Learning (DRL) setup for robot manipulation in the real world. It natively integrates well with the low-level CRISP Controllers."
authors = [{ name = "Luka Hofer", email = "luka.hofer@tum.de" }]
readme = "README.md"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["."]
include = ["crisp_drl*"]
